name: Verify
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  verify:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Lint, Test, And Coverage
      run: npm run lint && npm run cover
    - name: Coverage Upload
      if: ${{ success() }}
      run: cat reports/coverage/lcov.info | ./node_modules/.bin/coveralls
